### PR TITLE
unicode support for help_box and configuration support for other languages

### PR DESCRIPTION
**Pull request by qindapao**
Hello, I still use the pull request, I will explain my operation steps in the email, it should be right this time.

### CODE REVIEW

**Review by nkh — CHANGES_REQUESTED** [review]
Hi,  here's a better and simpler way to do this.

in setup/asciio_object/basic.pl:

DOUBLE_WIDTH_QR => qr/...../ # yes set a qr directly in the config, it will become part of the object

in lib/App/Asciio.pm:

delete sub set_double_width_char_global_expr_qr(), it's not needed, instead verify that DOUBLE_WIDTH_QR exists in the constructor, nothing more is needed 

same thing for global_double_width_char.... remove the sub altogether, the two functions that are in ToolFunc.pm should be part of the App::Asciio package and thus be called via an object, you can also remove EXPR_QR and instead use $self->{DOUBLE_WIDTH_QR}

**Review by nkh — CHANGES_REQUESTED** [review]
use $self->{TAB_AS_SPACES} directly, verify that it exists in the constructor

the $in_string variable is badly named, it says very little, $help_text is better.

**Comment by qindapao** [comment]
I see what you mean. It will take me 2 or 3 days to completely rectify Toolfuncs.pm. 
You can check back when I'm done I'm having a problem using map with object functions, usc_length If it becomes asciio-> usc _ length. map, the function doesn't seem to work like it used to. It's supposed to be a basic problem. I think I can handle it myself

**Comment by nkh** [comment]
hi, I hope it's OK we put the bar a bit higher now, it will also help you get better at Perl.

it's always a good idea to develop in a branch that's not main (I create and delete branches 10 times a day), you can always merge to your main branch before submitting a pull request.

you can have the code, you have problems making work, in a branch and push it to github, that allows me to pull it and look at it, merging is not always about merging in main, merging is just a cooperation tool, it can be used to work together on broken code.

I usually don't use pull requests, it's a github add-on to force people to use their website, it does help with communication and knowing if something would merge without conflict, but it's nothing that one must use (the linux kernel doesn't for example).


I propose that:

- in your repo, you make a new branch, say "broken_usc_length", then you push that branch to github. of course you can use your main branch but it's a bad idea as it should be kept outside development and broken changes.

- I will then pull that branch and propose fixes, I'll push it back in the repo so you can see them or merge it directly depending on how we decide to work with it.

**Comment by qindapao** [comment]
OK, I'll use the new method you submitted. I'll delete this pull request when I get home. 

I believe you, an experienced old engineer 

I have optimized some of this feature for the moment, but it may still not meet your requirements.After I create the branch, Help me optimize it. in case it meets your standards, it can also be integrated. I don't have time to systematically study perl right now. So I still need your help. 

I have been troubled by the work of the company recently, and my time is getting less and less. I went to the company to work overtime today. It's not easy to do something you're interested in in China. So sometimes I'm not very professional, The main thing is that there is too little time and too much time is spent on the company. A lot of trivial things, Sorry to complain too much, let you laugh

**Comment by nkh** [comment]
just push you branch and I'll look at it.

what environment are you working in? Linux/bash/vim?

I have some scripts I use with git that I can share with you if we have the same environment.

**Pull request closed without merging**
